version: "3.8"
services:
  postgres:
    container_name: pg
    image: postgres:alpine3.20
    environment:
      POSTGRES_DB: "tg_db"
      POSTGRES_USER: "tg_user"
      POSTGRES_PASSWORD: "pgtelegrambot"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d tg_db"]
      interval: 2h
      timeout: 30s
      retries: 2
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  db_data:
